import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import {Platform} from 'react-native';
import {operationalMetrics} from './domain';
import type {AppState} from '../data/types';
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function reportHTML(state:AppState,demo:boolean){const m=operationalMetrics(state);return `<!doctype html><html><head><meta charset="utf-8"><style>body{font-family:Arial,sans-serif;color:#141f2b;padding:36px}h1{color:#09386b}table{border-collapse:collapse;width:100%}td,th{padding:12px;border-bottom:1px solid #d3e1eb;text-align:left}.tag{color:#52697a}</style></head><body><h1>CareQueue</h1><h2>General OPD operations report</h2><p class="tag">${demo?'Demonstration · sample data':'Connected service'} · ${escape(new Date().toLocaleString('en-GB',{timeZone:'Asia/Colombo'}))}</p><table><tr><th>Status</th><td>${escape(state.serviceStatus)}</td></tr><tr><th>Now serving</th><td>${escape(state.nowServing)}</td></tr><tr><th>Waiting</th><td>${state.queue.filter(q=>q.status==='waiting').length}</td></tr><tr><th>Completed</th><td>${state.queue.filter(q=>q.status==='completed').length}</td></tr><tr><th>Clinical priority</th><td>${state.queue.filter(q=>q.priority==='clinical').length}</td></tr></table><p>Scope: retained General OPD session records; this is not a historical hospital report.</p><table><tr><th>Registered</th><td>${m.registered}</td></tr><tr><th>Missed</th><td>${m.missed}</td></tr><tr><th>Cancelled</th><td>${m.cancelled}</td></tr><tr><th>Delay updates (retained audit)</th><td>${m.delayUpdates}</td></tr><tr><th>Mean registration-to-call wait</th><td>${m.meanWaitMinutes===null?'No measured calls':m.meanWaitMinutes+' minutes'} (${m.measuredCalls} calls)</td></tr></table><h2>Operational audit</h2><table><tr><th>Time</th><th>Action</th><th>Role</th></tr>${state.audit.map(e=>`<tr><td>${escape(e.at)}</td><td>${escape(e.action)}</td><td>${escape(e.role)}</td></tr>`).join('')}</table><p class="tag">Patient names, phone numbers and clinical reasons are excluded.</p></body></html>`;}
export async function exportReport(state:AppState,demo:boolean){const html=reportHTML(state,demo);if(Platform.OS==='web'){await Print.printAsync({html});return;}const {uri}=await Print.printToFileAsync({html});if(await Sharing.isAvailableAsync())await Sharing.shareAsync(uri,{mimeType:'application/pdf',dialogTitle:'CareQueue OPD report'});return uri;}

export async function exportSlip(token:string,demo:boolean){
 if(!/^A\d{3,}$/.test(token))throw Error('Select an issued token first.');
 const html=`<!doctype html><html><head><meta charset="utf-8"></head><body style="font-family:Arial;padding:32px;text-align:center"><h1>CareQueue · General OPD</h1><p>${demo?'DEMONSTRATION TOKEN':'Issued queue token'}</p><h2 style="font-size:72px">${escape(token)}</h2><p>Room 04 · Follow staff instructions.</p><p>Clinical priority may change the order. Ask the counter if you miss a call.</p></body></html>`;
 await Print.printAsync({html});
}
