import fs from 'node:fs';
import test from 'node:test';
import {initializeTestEnvironment,assertFails,assertSucceeds} from '@firebase/rules-unit-testing';
import {doc,setDoc,getDoc,updateDoc} from 'firebase/firestore';
const environment=await initializeTestEnvironment({projectId:'demo-carequeue',firestore:{rules:fs.readFileSync('firebase/firestore.rules','utf8'),host:'127.0.0.1',port:8080}});
const patient=environment.authenticatedContext('patient-one').firestore(),other=environment.authenticatedContext('patient-two').firestore(),staff=environment.authenticatedContext('staff',{role:'staff'}).firestore(),admin=environment.authenticatedContext('admin',{role:'admin'}).firestore();
await environment.withSecurityRulesDisabled(async c=>{await setDoc(doc(c.firestore(),'operations','current'),{queue:[],audit:[],broadcasts:[],offlineActions:[],incidentVerified:false,nowServing:'—',serviceStatus:'open',updatedAt:'2026-10-05'});await setDoc(doc(c.firestore(),'tickets','patient-one'),{token:'A125',recovery:'none'});});
try{
 await test('profile owner can save settings; other patients and staff cannot read the profile',async()=>{await assertSucceeds(setDoc(doc(patient,'patients','patient-one'),{sms:false,appAlerts:true,language:'en',largeText:false}));await assertFails(getDoc(doc(other,'patients','patient-one')));await assertFails(getDoc(doc(staff,'patients','patient-one')));await assertFails(updateDoc(doc(patient,'patients','patient-one'),{role:'admin'}));});
 await test('staff may call patients but only admin can verify incidents',async()=>{await assertSucceeds(updateDoc(doc(staff,'operations','current'),{nowServing:'A125'}));await assertFails(updateDoc(doc(staff,'operations','current'),{incidentVerified:true}));await assertSucceeds(updateDoc(doc(admin,'operations','current'),{incidentVerified:true}));await assertFails(updateDoc(doc(patient,'operations','current'),{nowServing:'A126'}));});
 await test('recovery request must belong to the issued ticket and waits for staff',async()=>{await assertSucceeds(setDoc(doc(patient,'recoveryRequests','patient-one'),{patientId:'patient-one',token:'A125',status:'pending',requestedAt:new Date()}));await assertFails(updateDoc(doc(patient,'recoveryRequests','patient-one'),{status:'approved'}));await assertSucceeds(updateDoc(doc(staff,'recoveryRequests','patient-one'),{status:'approved'}));await assertFails(setDoc(doc(other,'recoveryRequests','patient-two'),{patientId:'patient-two',token:'A125',status:'pending',requestedAt:new Date()}));});
}finally{await environment.cleanup();}
