import {useState} from 'react';
import {Text,TextInput,Pressable,StyleSheet,ScrollView} from 'react-native';
import {useRouter} from 'expo-router';
import {login,configured,logout,initializeService,linkTicket} from '../services/firebase';
import {useStore} from '../services/store';
export default function Account(){const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[register,setRegister]=useState(false),[error,setError]=useState('');const router=useRouter();const [manualNote,setManualNote]=useState('');const [patientId,setPatientId]=useState(''),[token,setToken]=useState('');const {isLive,setDataMode,state,user,setRole,reset,execute}=useStore();
 async function submit(){setBusy(true);setError('');try{await login(email,password,register);router.replace('/');}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 return <ScrollView contentContainerStyle={s.page}><Text style={s.brand}>CareQueue</Text><Text style={s.title}>{isLive?'Welcome to CareQueue':'CareQueue demo'}</Text><Text style={s.caption}>{isLive?'Sign in to your hospital queue account.':'Explore the patient, staff and admin flows using sample data saved on this device.'}</Text>
 {isLive&&user?<><Text style={s.caption}>Signed in as {user.email}. Your account ID:</Text><Text selectable style={s.caption}>{user.uid}</Text>{state.role!=='patient'?<><Text style={s.title}>Link a patient token</Text><TextInput style={s.input} accessibilityLabel="Patient account ID" placeholder="Patient account ID" value={patientId} onChangeText={setPatientId}/><TextInput style={s.input} accessibilityLabel="Issued token" placeholder="Issued token" value={token} onChangeText={setToken}/><Pressable style={s.button} onPress={async()=>{try{await linkTicket(patientId,token);setError('Patient token linked.');}catch(e){setError(String(e));}}}><Text style={s.white}>Link issued token</Text></Pressable><TextInput style={s.input} accessibilityLabel="Manual queue action" placeholder="Manual queue action and token" value={manualNote} onChangeText={setManualNote}/><Pressable style={s.button} onPress={async()=>{try{if(!manualNote.trim())throw Error('Enter the action and token.');await execute('manualRecord',{'Manual action':manualNote});setManualNote('');setError('Saved on this device for staff reconciliation.');}catch(e){setError(String(e));}}}><Text style={s.white}>Save offline note</Text></Pressable>{state.role==='admin'?<Pressable style={s.button} onPress={async()=>{try{await initializeService();setError('Service initialized.');}catch(e){setError(String(e));}}}><Text style={s.white}>Initialize General OPD</Text></Pressable>:null}</>:null}<Pressable onPress={()=>router.replace('/')}><Text style={s.link}>Return to queue</Text></Pressable><Pressable onPress={()=>logout()}><Text style={s.link}>Sign out</Text></Pressable></>:isLive?<><TextInput style={s.input} accessibilityLabel="Email" value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="Email"/><TextInput style={s.input} accessibilityLabel="Password" value={password} onChangeText={setPassword} secureTextEntry placeholder="Password"/><Pressable style={s.button} disabled={busy||!configured} onPress={submit}><Text style={s.white}>{busy?'Signing in…':register?'Create patient account':'Sign in'}</Text></Pressable><Pressable onPress={()=>setRegister(v=>!v)}><Text style={s.link}>{register?'Already have an account? Sign in':'Create a patient account'}</Text></Pressable></>:<>{(['patient','staff','admin'] as const).map(role=><Pressable key={role} style={[s.input,state.role===role&&s.selected]} onPress={()=>{setRole(role);router.replace('/');}}><Text style={s.link}>Open {role} experience</Text></Pressable>)}</>}
 <Pressable onPress={()=>setDataMode(!isLive)}><Text style={s.link}>{isLive?'Explore with sample data':'Use my Firebase account'}</Text></Pressable>{!isLive?<Pressable onPress={()=>reset()}><Text style={s.link}>Reset sample data</Text></Pressable>:null}{error?<Text accessibilityRole="alert" style={s.error}>{error}</Text>:null}{isLive&&!configured?<Text style={s.error}>Firebase setup is incomplete.</Text>:null}</ScrollView>;
}
const s=StyleSheet.create({page:{flexGrow:1,padding:24,paddingTop:72,backgroundColor:'#f8fafc',gap:16},brand:{fontFamily:'Inter_700Bold',fontSize:20,color:'#09386b'},title:{fontFamily:'Inter_700Bold',fontSize:28,color:'#141f2b'},caption:{fontFamily:'Inter_400Regular',fontSize:14,lineHeight:22,color:'#52697a'},input:{padding:16,borderWidth:1,borderColor:'#d3e1eb',borderRadius:16,backgroundColor:'white',fontFamily:'Inter_400Regular'},selected:{borderColor:'#09386b'},button:{backgroundColor:'#09386b',padding:18,borderRadius:16,alignItems:'center'},white:{fontFamily:'Inter_700Bold',color:'white'},link:{fontFamily:'Inter_600SemiBold',color:'#09386b'},error:{color:'#be3036',fontFamily:'Inter_400Regular'}});
