import {useState} from 'react';
import {View,Text,TextInput,Pressable,ScrollView,StyleSheet} from 'react-native';
import {Redirect,useRouter} from 'expo-router';
import {useStore} from '../services/store';
import {patientsAhead,waitEstimate,operationalMetrics,orderedQueue} from '../services/domain';
import type {Command} from '../services/domain';
import {exportReport,exportSlip} from '../services/report';
import {linkTicket} from '../services/firebase';

export default function Manage(){
 const {state,isLive,user,ready,connected,execute,update}=useStore(),router=useRouter();
 const [token,setToken]=useState(''),[name,setName]=useState(''),[phone,setPhone]=useState(''),[uid,setUid]=useState(''),[caregiverUid,setCaregiverUid]=useState(''),[reason,setReason]=useState(''),[message,setMessage]=useState(''),[note,setNote]=useState(''),[feedback,setFeedback]=useState(''),[busy,setBusy]=useState(false);
 const [pending,setPending]=useState<{command:Command;fields:Record<string,string>;summary:string}|null>(null);
 if(!ready)return <Text>Loading account…</Text>;
 if(isLive&&!user)return <Redirect href="/account"/>;
 const metrics=operationalMetrics(state),staff=state.role!=='patient';
 const textStyle={fontSize:state.largeText?19:16,lineHeight:state.largeText?29:24};
 const field=(label:string,value:string,set:(v:string)=>void,multiline=false)=><View style={s.field}><Text style={[s.label,textStyle]}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={set} multiline={multiline} autoCapitalize={/account|phone/i.test(label)?'none':'sentences'} keyboardType={/phone/i.test(label)?'phone-pad':'default'} style={[s.input,textStyle]}/></View>;
 const button=(label:string,action:()=>void)=><Pressable accessibilityRole="button" disabled={busy} onPress={action} style={[s.button,busy&&{opacity:.5}]}><Text style={[s.white,textStyle]}>{label}</Text></Pressable>;
 const run=async(action:()=>Promise<unknown>)=>{setBusy(true);setFeedback('');try{await action();setFeedback('Saved successfully.');}catch(e){setFeedback(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 const review=(command:Command,fields:Record<string,string>,summary:string)=>{setFeedback('');setPending({command,fields,summary});};
 const selected=state.queue.find(q=>q.token===token);
 const status=state.ticketStatus||state.queue.find(q=>q.token===state.myToken)?.status;
 return <ScrollView contentContainerStyle={s.page} keyboardShouldPersistTaps="handled">
  <Text style={s.brand}>CareQueue</Text><Text style={s.heading}>{staff?'Queue operations':'My visit and settings'}</Text>
  <Text style={[s.text,textStyle]}>{isLive?'Connected Firebase account':'Demo · records saved on this device'} · {state.role}</Text>
  {button('Return to designed screens',()=>router.replace('/'))}
  {button('Account',()=>router.push('/account'))}
  {!connected?<Text accessibilityRole="alert" style={[s.warning,textStyle]}>Connection unavailable. Queue values are last known information. Ask the registration counter for assistance. Staff can record a manual note below.</Text>:null}
  {feedback?<Text accessibilityRole="alert" style={[s.warning,textStyle]}>{feedback}</Text>:null}
  {pending?<View style={s.card}><Text style={s.heading}>Review action</Text><Text style={[s.text,textStyle]}>{pending.summary}</Text>{button('Confirm action',()=>run(async()=>{await execute(pending.command,pending.fields);setPending(null);} ))}{button('Cancel review',()=>setPending(null))}</View>:null}
  <View style={s.card}><Text style={s.title}>General OPD</Text><Text style={[s.text,textStyle]}>Service: {state.serviceStatus} · Now serving: {state.nowServing}</Text><Text style={[s.text,textStyle]}>Last staff update: {state.updatedAt?new Date(state.updatedAt).toLocaleString('en-GB',{timeZone:'Asia/Colombo'}):'Waiting for first service update'}</Text>{state.broadcasts.map(b=><View key={b.id}><Text style={[s.text,textStyle]}>{b.message}</Text>{state.role==='admin'?button('Withdraw message',()=>review('removeBroadcast',{'Broadcast ID':b.id},'Withdraw this message from the current service feed. The audit remains.')):null}</View>)}</View>
  {state.sharedVisits?.length?<View style={s.card}><Text style={s.title}>Visits shared with me</Text>{state.sharedVisits.map(v=><Text key={v.id} style={[s.text,textStyle]}>Token {v.token} · {v.status} · {v.patientsAhead} patients ahead</Text>)}</View>:null}
  {!staff?<>
   <View style={s.card}><Text style={s.title}>Token {state.myToken}</Text><Text style={[s.text,textStyle]}>Visit: {status||'Not linked'} · {patientsAhead(state)} patients ahead</Text><Text style={[s.text,textStyle]}>Estimate: {waitEstimate(state)}. This uses 3–5 minutes per patient ahead and may change with clinical priority.</Text>
   {state.appAlerts&&status==='waiting'&&patientsAhead(state)<=2?<Text accessibilityRole="alert" style={[s.warning,textStyle]}>Your turn is approaching. Move towards Room 04 and wait for the staff call.</Text>:null}
   {status==='called'?<Text accessibilityRole="alert" style={[s.warning,textStyle]}>Your turn. Follow staff instructions at Room 04.</Text>:null}
   {status==='cancelled'?<Text accessibilityRole="alert" style={[s.warning,textStyle]}>Your visit was cancelled. Ask the registration counter for the next step.</Text>:null}
   <Text style={[s.text,textStyle]}>Recovery: {state.recovery}</Text>
   {button('Request staff recovery review',()=>review('requestRecovery',{},'Request staff review. This does not restore a queue position automatically.'))}
   </View>
   <View style={s.card}><Text style={s.title}>Preferences</Text>{button(`Large text: ${state.largeText?'on':'off'}`,()=>update({largeText:!state.largeText}))}{button(`App alerts: ${state.appAlerts?'on':'off'}`,()=>update({appAlerts:!state.appAlerts}))}{button(`SMS preference: ${state.sms?'on':'off'}`,()=>update({sms:!state.sms}))}<Text style={[s.text,textStyle]}>In-app queue messages work while connected. SMS and background push delivery are not connected.</Text>{button('Save preferences',()=>run(()=>execute('preferences')))}</View>
   <View style={s.card}><Text style={s.title}>Caregiver consent</Text><Text style={[s.text,textStyle]}>{state.caregiver?`Saved recipient: ${state.caregiver.name}`:'No caregiver consent saved'}. Consent covers queue/service updates only. A caregiver with a CareQueue account can view token, visit status and position only after you link their account ID. Confirm sharing again for each newly issued visit.</Text>{field('Caregiver name',name,setName)}{field('Caregiver phone',phone,setPhone)}{field('Caregiver account ID (optional)',caregiverUid,setCaregiverUid)}{button('Review caregiver consent',()=>review('caregiver',{'Caregiver name':name,'Phone number':phone,'Caregiver account ID':caregiverUid},`Save consent for ${name}, ${phone}, for queue and service updates. Account: ${caregiverUid||'consent only'}.`))}{state.caregiver?button('Revoke caregiver consent',()=>review('revokeCaregiver',{},'Remove the saved caregiver consent.')):null}</View>
  </>:<>
   <View style={s.card}><Text style={s.title}>Current-session report</Text><Text style={[s.text,textStyle]}>Registered: {metrics.registered} · Waiting: {metrics.waiting} · Completed: {metrics.completed} · Missed: {metrics.missed} · Cancelled: {metrics.cancelled}</Text><Text style={[s.text,textStyle]}>Mean registration-to-call wait: {metrics.meanWaitMinutes===null?'No measured calls':metrics.meanWaitMinutes+' min'} ({metrics.measuredCalls} calls). Delay updates in retained audit: {metrics.delayUpdates}.</Text>{button('Export operations report',()=>run(()=>exportReport(state,!isLive)))}</View>
   <View style={s.card}><Text style={s.title}>Register or edit a patient</Text>{field('Patient name',name,setName)}{field('Phone number (optional)',phone,setPhone)}{button('Review new registration',()=>review('register',{'Patient name':name,'Phone number':phone},`Register ${name} for General OPD.`))}
    <Text style={[s.text,textStyle]}>Select a record below to edit it or change its state.</Text>
    {state.queue.map(q=><Pressable key={q.token} accessibilityRole="button" accessibilityLabel={`Select ${q.token}`} style={s.record} onPress={()=>{setToken(q.token);setName(q.patientName);setPhone(q.phone);update({selectedToken:q.token});}}><Text style={[s.text,textStyle]}>{q.token} · {q.patientName} · {q.status}{q.priority==='clinical'?' · clinical priority':''}</Text></Pressable>)}
    {selected?<><Text style={[s.text,textStyle]}>Selected: {selected.token} · {selected.status}</Text>{button('Review edited details',()=>review('editPatient',{'Token':token,'Patient name':name,'Phone number':phone},`Update contact details for ${token}.`))}{button('Print token slip',()=>run(()=>exportSlip(token,!isLive)))}{selected.status==='called'?<>{button('Mark missed turn',()=>review('markMissed',{'Token':token},`Mark ${token} as missed.`))}{button('Complete consultation',()=>review('complete',{'Token':token},`Complete ${token}.`))}</>:null}{['waiting','missed'].includes(selected.status)?button('Cancel visit',()=>review('cancel',{'Token':token},`Cancel ${token}. Keep its history; it will no longer be called.`)):null}</>:null}
    <Text style={[s.text,textStyle]}>Next call: {orderedQueue(state.queue).find(q=>q.status==='waiting')?.token||'None'}</Text>{button('Review next call',()=>review('callNext',{},'Call the next waiting patient, respecting clinician-reviewed priority. The previous called consultation is completed.'))}{button('Recall current patient',()=>review('recall',{},`Recall ${state.nowServing}.`))}
   </View>
   <View style={s.card}><Text style={s.title}>Clinical priority</Text><Text style={[s.text,textStyle]}>Selected: {token||'Select a waiting record above'}. Apply only after a clinician has reviewed the case.</Text>{field('Clinical reason',reason,setReason,true)}{button('Review clinical priority',()=>review('priority',{'Token':token,'Clinical reason':reason},`Apply clinician-reviewed priority to ${token}. Reason: ${reason}`))}</View>
   {isLive?<View style={s.card}><Text style={s.title}>Link issued token</Text>{field('Patient account ID',uid,setUid)}{field('Issued token',token,setToken)}{button('Link patient account',()=>run(()=>linkTicket(uid,token)))}</View>:null}
   <View style={s.card}><Text style={s.title}>Pending recovery requests</Text>{state.recoveryRequests?.filter(r=>r.status==='pending').map(r=><View key={r.patientId}><Text style={[s.text,textStyle]}>{r.token} · pending staff review</Text>{button('Approve '+r.token,()=>review('approveRecovery',{'Patient ID':r.patientId,'Token':r.token},`Restore ${r.token} to waiting. Clinical priority rules still apply.`))}{button('Reject '+r.token,()=>review('rejectRecovery',{'Patient ID':r.patientId,'Token':r.token},`Reject recovery for ${r.token}. The patient must ask the counter for help.`))}</View>)}{!isLive&&state.recovery==='pending'?button('Review demo recovery',()=>review('approveRecovery',{'Token':state.myToken},'Approve the demo patient recovery.')):null}</View>
   <View style={s.card}><Text style={s.title}>Service message</Text>{field('Verified service update',message,setMessage,true)}{state.role==='admin'?button('Verify incident',()=>review('verifyIncident',{},'Confirm that the incident information has been checked with staff.')):null}{button('Review publication',()=>review('broadcast',{'Message':message},`Publish this General OPD service message in the app: ${message}`))}{state.role==='admin'?(['open','delay','unavailable'] as const).map(value=><View key={value}>{button('Set service '+value,()=>review('serviceStatus',{'Status':value},`Change General OPD status to ${value}.`))}</View>):null}</View>
   <View style={s.card}><Text style={s.title}>Manual continuity</Text><Text style={[s.text,textStyle]}>Use a numbered paper register during outages. Record the token, action and time; verify identity at the counter. Review each note against current records before reconciliation. Reconciliation archives notes; apply verified queue corrections separately.</Text>{field('Manual action and token',note,setNote,true)}{button('Save device-local note',()=>run(async()=>{await execute('manualRecord',{'Manual action':note});setNote('');}))}{state.offlineActions.map(a=><Text key={a.id} style={[s.text,textStyle]}>{a.at}: {a.action}</Text>)}{state.offlineActions.length?button('Review reconciliation',()=>review('reconcile',{},'I have reviewed every pending note against the current queue for duplicates and conflicts. Archive the notes in the audit and clear this device’s pending list.')):null}</View>
   <View style={s.card}><Text style={s.title}>Audit history</Text>{state.audit.slice(0,30).map(e=><Text key={e.id} style={[s.text,textStyle]}>{e.at} · {e.role} · {e.action} {e.detail||''}</Text>)}</View>
  </>}
  {button('Open token display',()=>router.push('/display'))}
 </ScrollView>;
}
const s=StyleSheet.create({page:{padding:24,paddingTop:60,paddingBottom:60,gap:16,backgroundColor:'#f8fafc',maxWidth:800,width:'100%',alignSelf:'center'},brand:{fontFamily:'Inter_700Bold',color:'#09386b',fontSize:22},heading:{fontFamily:'Inter_700Bold',fontSize:26,color:'#141f2b'},title:{fontFamily:'Inter_700Bold',fontSize:21,color:'#09386b'},card:{backgroundColor:'white',padding:20,borderRadius:16,borderWidth:1,borderColor:'#d3e1eb',gap:14},text:{fontFamily:'Inter_400Regular',color:'#141f2b'},label:{fontFamily:'Inter_600SemiBold',color:'#52697a'},field:{gap:8},input:{borderWidth:1,borderColor:'#d3e1eb',borderRadius:12,padding:14,backgroundColor:'#f8fafc',color:'#141f2b',minHeight:52},button:{padding:16,minHeight:52,backgroundColor:'#09386b',borderRadius:12,alignItems:'center'},white:{fontFamily:'Inter_600SemiBold',color:'white'},warning:{backgroundColor:'#fff7e2',color:'#7a4300',padding:16,borderRadius:12},record:{padding:16,borderWidth:1,borderColor:'#d3e1eb',borderRadius:12,minHeight:52}});
