import React,{memo} from 'react';
import {View,Text,Pressable,ScrollView,Image,TextInput,Platform,type TextStyle,type ViewStyle,type ImageStyle} from 'react-native';
import Svg,{SvgXml,Defs,Filter,FeGaussianBlur,Rect} from 'react-native-svg';
import {Asset} from 'expo-asset';
import MaskedView from '@react-native-masked-view/masked-view';
import {LinearGradient} from 'expo-linear-gradient';
import svgData from '../data/svg.json';
import {assets} from '../data/assets';
import type {DesignNode,DesignScreen,AppState} from '../data/types';
import {designStyles,inheritedText,viewOnly,type DesignStyle} from './designStyles';
import {patientsAhead,nextToken} from '../services/domain';
import {resolveDesignEdge} from '../services/designNavigation';
export interface RenderContext {screen:DesignScreen;state:AppState;fields:Record<string,string>;onField:(label:string,value:string)=>void;onAction:(label:string,to?:string)=>void;busy:boolean;scale:number;isLive:boolean;}
function allText(n:DesignNode):string {return n.text||n.actionLabel||n.children?.map(allText).join(' ').trim()||'';}
function adjust(style:DesignStyle,scale:number):DesignStyle{if(scale===1)return style;const next={...style};for(const k of Object.keys(next)){const key=k as keyof DesignStyle;const v=next[key];if(typeof v==='number'&&!['opacity','flexGrow','flexShrink','flexBasis','zIndex'].includes(k))(next as Record<string,unknown>)[k]=v*scale;}return next;}
function dynamicText(text:string,ctx:RenderContext,owner?:string){let value=text;
 if(owner==='123:181')value=String(patientsAhead(ctx.state));
 if(['I408:1891;114:6','I409:1529;114:6'].includes(owner||''))value=String(ctx.state.audit.length);
 if(owner==='I408:1895;114:6')value=String(ctx.state.audit.filter(e=>e.action==='priority').length);
 if(['I408:1900;114:6','I409:1533;114:6'].includes(owner||''))value=String(ctx.state.broadcasts.length);
 if(owner==='I408:1904;114:6')value=ctx.state.audit[0]?new Date(ctx.state.audit[0].at).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'}):'—';
 if(owner==='I408:1904;114:7')value=ctx.state.audit[0]?.action.replace(/([A-Z])/g,' $1').toLowerCase()||'No action recorded';
 if(['139:209','I407:1572;114:6','I407:1682;114:6'].includes(owner||''))value=String(ctx.state.queue.filter(q=>q.status==='waiting').length);
 if(['139:222','I407:1576;114:6','I407:1691;114:6'].includes(owner||''))value=String(ctx.state.queue.filter(q=>q.highRisk||q.priority==='clinical').length).padStart(owner==='139:222'?2:1,'0');
 if(['139:223','154:453'].includes(ctx.screen.id))value=value.replaceAll('A128',nextToken(ctx.state));
 if(ctx.screen.id==='154:453'&&text==='Patient A128')value=ctx.fields['Patient name']||'Patient';
 if(ctx.fields['Message']&&value.startsWith('The medical officer is delayed.'))value=ctx.fields['Message'];
 if(ctx.isLive){value=value.replaceAll('Kamala Perera',ctx.state.patientName||'Patient').replaceAll('Kamala',(ctx.state.patientName||'Patient').split(' ')[0]);if(value==='Friday, 18 Sep 2026')value=new Date().toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'short',year:'numeric',timeZone:'Asia/Colombo'});if(/Updated 10:42 AM/.test(value)&&!ctx.state.updatedAt)value='Waiting for service update';if(value==='18 min')value='—';if(value==='7 / 8')value=ctx.state.serviceStatus==='open'?'1 / 1':'0 / 1';if(value==='11 waiting · Room 02 staff active')value='Not connected';if(/184 served today|Efficiency \+8.4%|General OPD · \+12%/.test(value))value='—';}
 if(/24 waiting · Room 04 session active/.test(value))value=`${ctx.state.queue.filter(q=>q.status==='waiting').length} waiting · Room 04`;
 if(ctx.screen.id==='154:528'){const latest=ctx.state.queue.at(-1);if(latest)value=value.replaceAll('Patient A128',latest.patientName).replaceAll('A128',latest.token).replaceAll('A147',latest.token).replaceAll('Saman Jayawardena',latest.patientName);}
 if(['154:605'].includes(ctx.screen.id)){const next=ctx.state.queue.find(q=>q.status==='waiting'&&q.priority==='clinical')||ctx.state.queue.find(q=>q.status==='waiting');value=value.replaceAll('A120',next?.token||'—');}
 if(ctx.screen.id==='154:675')value=value.replaceAll('A120',ctx.state.nowServing);
 if(ctx.state.serviceStatus!=='open'){if(value==='General OPD • Open')value=`General OPD • ${ctx.state.serviceStatus==='delay'?'Delayed':ctx.state.serviceStatus==='offline'?'Offline':'Unavailable'}`;if(value==='On track')value=ctx.state.serviceStatus==='delay'?'Delayed':'Check service status';if(value==='Estimated 20–30 min'||value==='20–30 min')value=ctx.state.serviceStatus==='delay'?'Estimated 35–50 min':'Estimate unavailable';}
 if(ctx.isLive&&['139:376','154:813'].includes(ctx.screen.id)){const selected=ctx.state.queue.find(q=>q.token===ctx.state.selectedToken)||ctx.state.queue.find(q=>q.status==='waiting');value=value.replaceAll('A121',selected?.token||'—').replaceAll('Sunil Perera',selected?.patientName||'No patient selected');}
 if(ctx.isLive&&['139:445','154:957','154:1025'].includes(ctx.screen.id)){const request=ctx.state.recoveryRequests?.find(r=>r.status==='pending');const record=ctx.state.queue.find(q=>q.patientId===request?.patientId);value=value.replaceAll('A125',request?.token||'—').replaceAll('Kamala Perera',record?.patientName||'No pending request');}
 if(ctx.isLive&&['138:4','139:297'].includes(ctx.screen.id)){const waiting=ctx.state.queue.filter(q=>q.status==='waiting');for(const [i,original] of ['A120','A121','A122'].entries())value=value.replaceAll(original,waiting[i]?.token||'—');for(const [i,original] of ['Sumithra K.','Sunil Perera','Janaki Perera'].entries())value=value.replaceAll(original,waiting[i]?.patientName||'No waiting patient');if(/waiting|Routine Check|Respiratory/i.test(value)&&!waiting.length)value='No waiting patients';}
 if(ctx.state.nowServing!=='A119')value=value.replaceAll('A119',ctx.state.nowServing);
 if(ctx.screen.id==='151:769'&&ctx.state.scannedToken)value=value.replaceAll('A125',ctx.state.scannedToken);
 if(ctx.state.myToken!=='A125')value=value.replaceAll('A125',ctx.state.myToken);
 for(const [key,original] of Object.entries(fieldDefaults[ctx.screen.role]))if(ctx.fields[key]&&ctx.fields[key]!==original)value=value.replaceAll(original,ctx.fields[key]);
 if(value==='6 patients ahead')value=`${patientsAhead(ctx.state)} patients ahead`;
 if(ctx.state.updatedAt&&ctx.state.updatedAt!=='2026-09-18T05:12:00.000Z'&&/Updated 10:42 AM/.test(value))value=value.replace('Updated 10:42 AM',`Updated ${new Date(ctx.state.updatedAt).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}`);
 return value;
}
export const fieldDefaults:Record<string,Record<string,string>>={patient:{'Caregiver name':'Nadeesha Perera','Phone number':'+94 77 123 4567','Token number':'A125','Registration reference':'A125'},staff:{'Patient name':'Saman Jayawardena','Phone number':'+94 77 456 8910','Service':'General OPD','Reason category':'Clinician-confirmed urgency','Clinical review':'Confirmed · 10:54 AM'},admin:{}};
const OriginalAsset=memo(function OriginalAsset({name,style,alt}:{name:string;style:DesignStyle;alt?:string}){const source=assets[name];if(!source)return <Text accessibilityRole="alert">Missing design asset</Text>;return name.endsWith('.svg')?<View style={viewOnly(style)} accessible={Boolean(alt)} accessibilityLabel={alt}><SvgXml xml={(svgData as Record<string,string>)[name]} width="100%" height="100%"/></View>:<Image source={source} style={style as ImageStyle} accessibilityLabel={alt} resizeMode="cover"/>;});
function Field({node,ctx}:{node:DesignNode;ctx:RenderContext}){const p=node.props!,label=p.label||'Phone number',style=adjust(designStyles(node.classes),ctx.scale);return <View style={viewOnly(style)}><Text style={{fontFamily:'Inter_400Regular',fontSize:12*ctx.scale,lineHeight:18*ctx.scale,color:'#52697a'}}>{label}</Text><TextInput accessibilityLabel={node.actionLabel||allText(node)||label} style={{backgroundColor:'white',borderColor:'#d3e1eb',borderWidth:1,borderRadius:16*ctx.scale,padding:16*ctx.scale,width:'100%',fontFamily:'Inter_600SemiBold',color:'#141f2b',fontSize:14*ctx.scale,minHeight:52*ctx.scale}} value={ctx.fields[label]??p.value??''} onChangeText={value=>ctx.onField(label,value)} keyboardType={/phone|contact/i.test(label)?'phone-pad':'default'} autoCapitalize={/reference|token/i.test(label)?'characters':'sentences'} multiline={/reason|message|action/i.test(label)} /><Text style={{fontFamily:'Inter_400Regular',fontSize:12*ctx.scale,lineHeight:18*ctx.scale,color:'#52697a'}}>{p.helper}</Text></View>;}
export function DesignRenderer({node,ctx,inherit={},root=false,inScroll=false,textOwner}:{node:DesignNode;ctx:RenderContext;inherit?:TextStyle;root?:boolean;inScroll?:boolean;textOwner?:string}){
 let style=adjust(designStyles(node.classes),ctx.scale);
 if(root)style={...style,width:'100%',height:'100%',borderWidth:0,borderRadius:0,flexDirection:'column'};
 if(inScroll&&style.position==='absolute')style={...style,position:'relative',left:undefined,right:undefined,top:undefined};
 if(ctx.state.largeText){if(style.fontSize)style={...style,fontSize:style.fontSize*1.15};if(style.lineHeight)style={...style,lineHeight:style.lineHeight*1.15};}
 if(node.tag==='text'){const text=dynamicText(node.text||'',ctx,textOwner);return <Text style={{...inherit,fontFamily:inherit.fontFamily||'Inter_400Regular'}}>{text}</Text>;}
 if(node.classes?.split(' ').includes('contents'))return <>{node.children?.map((n,i)=><DesignRenderer key={i} node={n} ctx={ctx} inherit={inherit}/>)}</>;
 if(node.tag==='fragment')return <>{node.children?.map((n,i)=><DesignRenderer key={i} node={n} ctx={ctx} inherit={inherit}/>)}</>;
 if(node.tag==='img')return <OriginalAsset name={node.asset!} style={style} alt={node.alt}/>;
 if(node.component==='CareQueueField')return <Field node={node} ctx={ctx}/>;
 const textStyle={...inherit,...inheritedText(style)};
 const foundEdge=resolveDesignEdge(node,ctx.screen);const branches=foundEdge?.branches;const verified=branches?.[0]?.variable==='VariableID:405:2127'?ctx.state.incidentVerified:ctx.state.broadcasts.length>0;const edge=branches?{...foundEdge,to:branches[verified?0:1]?.to}:foundEdge;const edgeLabel=edge?.name;const label=edgeLabel&&!/^(Button|Container|Section|Background)/.test(edgeLabel)?edgeLabel:dynamicText(node.actionLabel||allText(node),ctx,node.id);
 if(node.component==='CareQueueRow'&&node.props?.title==='SMS updates'){
  const enabled=ctx.state.sms;return <Pressable accessibilityRole="switch" accessibilityState={{checked:enabled}} accessibilityLabel="SMS updates" style={viewOnly(style)} onPress={()=>ctx.onAction('Toggle SMS',edge?.to)}><Text style={{fontFamily:'Inter_700Bold',fontSize:14*ctx.scale,color:'#09386b',backgroundColor:'#f0f7ff',padding:12*ctx.scale,borderRadius:12*ctx.scale}}>{enabled?'✓':'○'}</Text><View style={{flex:1,gap:4*ctx.scale}}><Text style={{fontFamily:'Inter_600SemiBold',fontSize:14*ctx.scale,color:'#141f2b'}}>SMS updates</Text><Text style={{fontFamily:'Inter_400Regular',fontSize:12*ctx.scale,color:'#52697a'}}>{enabled?'ON':'OFF'} · +94 77 123 4567</Text></View></Pressable>;
 }
 if(node.component==='CareQueueRow'&&node.props?.title==='App notifications')return <Pressable accessibilityRole="switch" accessibilityState={{checked:ctx.state.appAlerts}} accessibilityLabel="App notifications" style={viewOnly(style)} onPress={()=>ctx.onAction('Toggle app alerts',edge?.to)}><Text style={{fontFamily:'Inter_700Bold',fontSize:14*ctx.scale,color:'#09386b',backgroundColor:'#f0f7ff',padding:12*ctx.scale,borderRadius:12*ctx.scale}}>{ctx.state.appAlerts?'✓':'○'}</Text><View style={{flex:1,gap:4*ctx.scale}}><Text style={{fontFamily:'Inter_600SemiBold',fontSize:14*ctx.scale,color:'#141f2b'}}>App notifications</Text><Text style={{fontFamily:'Inter_400Regular',fontSize:12*ctx.scale,color:'#52697a'}}>{ctx.state.appAlerts?'ON':'OFF'} · queue and service updates</Text></View></Pressable>;
 const children=node.children?.map((child,i)=><DesignRenderer key={`${child.id||child.key||child.tag}-${i}`} node={child} ctx={ctx} inherit={textStyle} inScroll={node.classes?.includes('overflow-y-auto')} textOwner={node.id||textOwner}/>);
 if(node.tag==='p'&&((ctx.screen.id==='35:374'&&node.id==='I408:1681;114:7')||(ctx.screen.id==='140:243'&&node.children?.some(c=>c.binding==='body')&&inherit.fontSize===14*ctx.scale)))return <TextInput accessibilityLabel="Service update message" style={{...inherit,...style,padding:0}} multiline value={ctx.fields['Message']||allText(node)} onChangeText={v=>ctx.onField('Message',v)}/>;
 if(['35:537','405:2125'].includes(ctx.screen.id)&&node.id?.match(/^I(?:408:(?:1909|1913|1917|1921)|409:(?:1538|1543|1547|1551|1555));114:[567]$/)){
  const cardIds=ctx.screen.id==='35:537'?['408:1909','408:1913','408:1917','408:1921']:['409:1538','409:1543','409:1547','409:1551','409:1555'];
  const event=ctx.state.audit[cardIds.indexOf(node.id.split(';')[0].slice(1))];
  const value=node.id.endsWith(':5')?event?'RECORDED':'AUDIT':node.id.endsWith(':6')?event?event.action.replace(/([A-Z])/g,' $1').toLowerCase():'No action recorded':event?`Time: ${new Date(event.at).toLocaleString('en-GB',{timeZone:'Asia/Colombo'})}\nActor: ${event.role}\n${event.detail||'Confirmed operational action'}`:'Actions appear after confirmed changes.';
  return <Text style={{...inherit,...style,lineHeight:node.id.endsWith(':7')?21*ctx.scale:style.lineHeight}}>{value}</Text>;
 }
 if(node.tag==='p')return <Text accessibilityRole={edge?.to?'button':undefined} onPress={edge?.to?()=>ctx.onAction(label,edge.to):undefined} style={{...inherit,...style,fontFamily:style.fontFamily||inherit.fontFamily||'Inter_400Regular',includeFontPadding:false}}>{children}</Text>;
 if(node.classes?.includes('overflow-y-auto'))return <ScrollView style={{width:'100%',flex:1}} contentContainerStyle={{minHeight:'100%'}} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>{children}</ScrollView>;
 if(ctx.isLive&&(node.name==='Editable chart'||ctx.screen.id==='138:4'&&node.name==='SVG'))return <View style={{...viewOnly(style),justifyContent:'center',alignItems:'center'}}><Text style={{fontFamily:'Inter_400Regular',color:'#52697a',fontSize:12}}>Historical flow data is not connected</Text></View>;
 if(node.maskAsset){const uri=Asset.fromModule(assets[node.maskAsset]).uri;const position=node.classes?.match(/mask-position-\[([^\]]+)\]/)?.[1].split('_').map(parseFloat)||[0,0];const size=node.classes?.match(/mask-size-\[([^\]]+)\]/)?.[1].split('_').map(parseFloat)||[252,155];if(Platform.OS==='web')return <View style={{...viewOnly(style),maskImage:`url("${uri}")`,maskPosition:`${position[0]}px ${position[1]}px`,maskSize:`${size[0]}px ${size[1]}px`,maskRepeat:'no-repeat'} as ViewStyle}>{children}</View>;return <MaskedView style={viewOnly(style)} maskElement={<OriginalAsset name={node.maskAsset} style={{position:'absolute',left:position[0]*ctx.scale,top:position[1]*ctx.scale,width:size[0]*ctx.scale,height:size[1]*ctx.scale}}/>}>{children}</MaskedView>;}
 if(node.classes?.includes('blur-[32px]')){const outer={...viewOnly(style),backgroundColor:undefined,overflow:'visible' as const};return <View style={outer}><Svg width="100%" height="100%" viewBox="0 0 160 160" style={{overflow:'visible'}}><Defs><Filter id={node.id?.replace(':','-')||'glow'} x="-100%" y="-100%" width="300%" height="300%"><FeGaussianBlur stdDeviation={32}/></Filter></Defs><Rect width={160} height={160} rx={80} fill="rgba(255,255,255,0.1)" filter={`url(#${node.id?.replace(':','-')||'glow'})`}/></Svg></View>;}
 if(node.classes?.includes('bg-gradient-to-l'))return <LinearGradient colors={['rgba(255,255,255,0)','rgba(255,255,255,0.05)']} start={{x:0,y:0}} end={{x:1,y:0}} style={viewOnly(style)}>{children}</LinearGradient>;
 if(edge?.to||node.classes?.includes('cursor-pointer')&&node.tag==='a')return <Pressable style={viewOnly(style)} onPress={()=>ctx.onAction(label,edge?.to)} disabled={ctx.busy} accessibilityRole="button" accessibilityLabel={node.actionLabel||allText(node)||label} testID={node.id} hitSlop={2}>{children}</Pressable>;
 if(node.component==='CareQueueButton')return <Pressable style={viewOnly(style)} onPress={()=>ctx.onAction(label,edge?.to)} disabled={ctx.busy} accessibilityRole="button" accessibilityLabel={node.actionLabel||allText(node)||label}>{children}</Pressable>;
 const brand=node.name==='Heading 1';return <View style={viewOnly(style)} testID={node.id} onTouchEnd={brand&&Platform.OS!=='web'?()=>{}:undefined}>{children}</View>;
}
